cw_logging:
  expire_events_after_days: '90'
  log_sets:
    rpm_linux:
      expire_events_after_days: '90'
      log_groups:
        audit:
          sources:
            audit:
              path: "/var/log/audit/audit.log"
              log_stream_name: "{instance_id}"
        secure:
          sources:
            secure:
              path: "/var/log/secure"
              log_stream_name: "{instance_id}"
        messages:
          sources:
            messages:
              path: "/var/log/messages"
              log_stream_name: "{instance_id}"
        yum:
          sources:
            yum:
              path: "/var/log/yum.log"
              log_stream_name: "{instance_id}"
    dpkg_linux:
      expire_events_after_days: '90'
      log_groups:
        auth:
          sources:
            audit:
              path: "/var/log/auth.log"
              log_stream_name: "{instance_id}"
        syslog:
          sources:
            secure:
              path: "/var/log/syslog"
              log_stream_name: "{instance_id}"
        daemon:
          sources:
            messages:
              path: "/var/log/daemon.log"
              log_stream_name: "{instance_id}"
        dpkg:
          sources:
            dpkg:
              path: "/var/log/dpkg.log"
              log_stream_name: "{instance_id}"
        kern:
          sources:
            kern:
              path: "/var/log/kern.log"
              log_stream_name: "{instance_id}"
    apache:
      log_groups:
        access:
          expire_events_after_days: '90'
          sources:
            access:
              path: "/var/log/httpd/access.log"
              log_stream_name: "access-{instance_id}"
        error:
          expire_events_after_days: '90'
          sources:
            error:
              path: "/var/log/httpd/error.log"
              log_stream_name: "error-{instance_id}"
